First try (jupyter client no found)
Exception occurred:
File
"/Users/jsick/.virtualenvs/sqr-019/lib/python3.5/site-packages/traitlets/utils/importstring.py",
line 34, in import_item
module = __import__(package, fromlist=[obj])
ImportError: No module named 'jupyter_client'
The full traceback has been saved in
/var/folders/sq/89jdjpmd1f52y795rzxs3xk00000gn/T/sphinx-err-pa2rgz10.log,
if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better
error message can be provided next time.
A bug report can be filed in the tracker at
<https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1